upstream vscg_app {
    server 127.0.0.1:3000;
}

server {
    listen 80;
    server_name formation.valuestream-consulting.com;

    client_max_body_size 25M;

    location / {
        proxy_pass http://vscg_app;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
